services:

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566" # Use port 4566 for LocalStack's services like  S3
    environment:
      - SERVICES=s3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
